train_file: ['/mnt/data/tianqiwei/VTT/outputs/coattack/data/anno/vqa_train.json',
             '/mnt/data/tianqiwei/VTT/outputs/coattack/data/anno/vqa_val.json']
            #  ,'/mnt/data/tianqiwei/VTT/outputs/coattack/data/anno/vg_qa.json']
             
test_file: ['/mnt/data/tianqiwei/VTT/outputs/coattack/data/anno/vqa_test.json']
answer_list: '/mnt/data/tianqiwei/VTT/outputs/coattack/data/anno/answer_list.json'

vqa_root: '/mnt/data/tianqiwei/VTT/outputs/coattack/data/coco/' #train2014/
vg_root: '/mnt/data/tianqiwei/VTT/outputs/coattack/data/coco/'  #image/

image_res: 384
batch_size_train: 32 
batch_size_test: 64
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







